apiVersion: v1
kind: Pod
metadata:
  name: vladislav-lamzenkov-app-1
  labels:
    app: vladislav-lamzenkov-app
spec:
  containers:
    - name: vladislav-lamzenkov-container
      image: mcflydesigner/ls-lab4-vl:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: vladislav-lamzenkov-app-2
  labels:
    app: vladislav-lamzenkov-app
spec:
  containers:
    - name: vladislav-lamzenkov-container
      image: mcflydesigner/ls-lab4-vl:latest
      ports:
        - containerPort: 8080
