apiVersion: v1
kind: Service
metadata:
  name: vladislav-lamzenkov-nodeport
spec:
  selector:
    app: vladislav-lamzenkov-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
