apiVersion: v1
kind: Service
metadata:
  name: vladislav-lamzenkov-svc
  namespace: dev
spec:
  selector:
    app: vladislav-lamzenkov-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
